# Generated by Django 5.0.4 on 2024-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
